name: Robot Redaksi IDI Denpasar

on:
  schedule:
    # Jalan otomatis setiap jam 08:00 dan 17:00 WIB
    - cron: '0 1,10 * * *' 
  workflow_dispatch: # Tombol ajaib biar kita bisa tes jalankan manual kapan saja

jobs:
  jalankan_robot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Mengambil Kode
      uses: actions/checkout@v3

    - name: Menyiapkan Mesin Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Membangunkan Robot auto_news.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python auto_news.py
